version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Use a named volume for persistence instead of a bind mount
      - chroma_data:/app/db/chroma
      - ${DATA_STORE_PATH:-./docs}:/app/docs
    environment:
      - CHROMA_PATH=/app/db/chroma
      - DATA_STORE_PATH=/app/docs
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped

volumes:
  chroma_data:
    # This ensures the volume is pre-populated with the data from the image
    driver: local
