services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Use a named volume for persistent ChromaDB storage
      - chroma_data:/app/db/chroma
    environment:
      - CHROMA_PATH=/app/db/chroma
      - DATA_STORE_PATH=/app/db/knowledge_base
      - GOOGLE_API_KEY="AIzaSyCqocy4RGw08bvimmzZRWBV37rm1aq5bHY"
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local
